/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module adder_demo(clk, rst_n, A, B, S, en);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input A;
  wire A;
  input B;
  wire B;
  output S;
  wire S;
  input en;
  wire en;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire \a_reg[0] ;
  wire \a_reg[1] ;
  wire \a_reg[2] ;
  wire \a_reg[3] ;
  wire \a_reg[4] ;
  wire \a_reg[5] ;
  wire \a_reg[6] ;
  wire \a_reg[7] ;
  wire \add0.b[0] ;
  wire \add0.b[1] ;
  wire \add0.b[2] ;
  wire \add0.b[3] ;
  wire \add0.b[4] ;
  wire \add0.b[5] ;
  wire \add0.b[6] ;
  wire \add0.b[7] ;
  sky130_fd_sc_hd__xor2_1 _044_ (
    .A(\add0.b[6] ),
    .B(\a_reg[6] ),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _045_ (
    .A(\add0.b[5] ),
    .SLEEP(\a_reg[5] ),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_0 _046_ (
    .A(\add0.b[1] ),
    .B(\a_reg[1] ),
    .X(_018_)
  );
  sky130_fd_sc_hd__xor2_1 _047_ (
    .A(\add0.b[1] ),
    .B(\a_reg[1] ),
    .X(_019_)
  );
  sky130_fd_sc_hd__and3_1 _048_ (
    .A(\add0.b[0] ),
    .B(\a_reg[0] ),
    .C(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__a31o_1 _049_ (
    .A1(\add0.b[0] ),
    .A2(\a_reg[0] ),
    .A3(_019_),
    .B1(_018_),
    .X(_021_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _050_ (
    .A(\add0.b[2] ),
    .SLEEP(\a_reg[2] ),
    .X(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _051_ (
    .A(\add0.b[3] ),
    .B(\a_reg[3] ),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a22oi_1 _052_ (
    .A1(\add0.b[2] ),
    .A2(\a_reg[2] ),
    .B1(\add0.b[3] ),
    .B2(\a_reg[3] ),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _053_ (
    .A(\add0.b[3] ),
    .B(\a_reg[3] ),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _054_ (
    .A1(\add0.b[2] ),
    .A2(\a_reg[2] ),
    .B1(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _055_ (
    .A(_023_),
    .B(_024_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a31oi_1 _056_ (
    .A1(_021_),
    .A2(_022_),
    .A3(_026_),
    .B1(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _057_ (
    .A(\add0.b[4] ),
    .B(\a_reg[4] ),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _058_ (
    .A(\add0.b[4] ),
    .B(\a_reg[4] ),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _059_ (
    .A(\add0.b[5] ),
    .B(\a_reg[5] ),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o211ai_1 _060_ (
    .A1(_028_),
    .A2(_029_),
    .B1(_030_),
    .C1(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _061_ (
    .A1(_017_),
    .A2(_032_),
    .B1(_016_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2b_1 _062_ (
    .A_N(_029_),
    .B(_030_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _063_ (
    .A(\add0.b[0] ),
    .B(\a_reg[0] ),
    .C(_019_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _064_ (
    .A(_017_),
    .B(_031_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand4_1 _065_ (
    .A(\add0.b[6] ),
    .B(\a_reg[6] ),
    .C(\add0.b[7] ),
    .D(\a_reg[7] ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xor2_1 _066_ (
    .A(_030_),
    .B(_036_),
    .X(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _067_ (
    .A1(_020_),
    .A2(_035_),
    .B1(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a211o_1 _068_ (
    .A1(_028_),
    .A2(_034_),
    .B1(_037_),
    .C1(_039_),
    .X(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _069_ (
    .A1(_021_),
    .A2(_025_),
    .B1(_022_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _070_ (
    .A1(_021_),
    .A2(_026_),
    .B1(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o221ai_1 _071_ (
    .A1(_028_),
    .A2(_034_),
    .B1(_041_),
    .B2(_026_),
    .C1(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _072_ (
    .A(_033_),
    .B(_040_),
    .C(_043_),
    .Y(S)
  );
  sky130_fd_sc_hd__mux2_1 _073_ (
    .A0(\a_reg[1] ),
    .A1(\a_reg[0] ),
    .S(en),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _074_ (
    .A0(\a_reg[2] ),
    .A1(\a_reg[1] ),
    .S(en),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _075_ (
    .A0(\a_reg[3] ),
    .A1(\a_reg[2] ),
    .S(en),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _076_ (
    .A0(\a_reg[4] ),
    .A1(\a_reg[3] ),
    .S(en),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _077_ (
    .A0(\a_reg[5] ),
    .A1(\a_reg[4] ),
    .S(en),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _078_ (
    .A0(\a_reg[6] ),
    .A1(\a_reg[5] ),
    .S(en),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _079_ (
    .A0(\a_reg[7] ),
    .A1(\a_reg[6] ),
    .S(en),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _080_ (
    .A0(\add0.b[0] ),
    .A1(B),
    .S(en),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _081_ (
    .A0(\add0.b[1] ),
    .A1(\add0.b[0] ),
    .S(en),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _082_ (
    .A0(\add0.b[2] ),
    .A1(\add0.b[1] ),
    .S(en),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(\add0.b[3] ),
    .A1(\add0.b[2] ),
    .S(en),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _084_ (
    .A0(\add0.b[4] ),
    .A1(\add0.b[3] ),
    .S(en),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _085_ (
    .A0(\add0.b[5] ),
    .A1(\add0.b[4] ),
    .S(en),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _086_ (
    .A0(\add0.b[6] ),
    .A1(\add0.b[5] ),
    .S(en),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _087_ (
    .A0(\add0.b[7] ),
    .A1(\add0.b[6] ),
    .S(en),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _088_ (
    .A0(\a_reg[0] ),
    .A1(A),
    .S(en),
    .X(_015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _089_ (
    .CLK(clk),
    .D(_000_),
    .Q(\a_reg[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _090_ (
    .CLK(clk),
    .D(_001_),
    .Q(\a_reg[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _091_ (
    .CLK(clk),
    .D(_002_),
    .Q(\a_reg[3] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _092_ (
    .CLK(clk),
    .D(_003_),
    .Q(\a_reg[4] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _093_ (
    .CLK(clk),
    .D(_004_),
    .Q(\a_reg[5] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _094_ (
    .CLK(clk),
    .D(_005_),
    .Q(\a_reg[6] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _095_ (
    .CLK(clk),
    .D(_006_),
    .Q(\a_reg[7] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _096_ (
    .CLK(clk),
    .D(_007_),
    .Q(\add0.b[0] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _097_ (
    .CLK(clk),
    .D(_008_),
    .Q(\add0.b[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(clk),
    .D(_009_),
    .Q(\add0.b[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(clk),
    .D(_010_),
    .Q(\add0.b[3] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(clk),
    .D(_011_),
    .Q(\add0.b[4] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(clk),
    .D(_012_),
    .Q(\add0.b[5] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(clk),
    .D(_013_),
    .Q(\add0.b[6] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(clk),
    .D(_014_),
    .Q(\add0.b[7] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(clk),
    .D(_015_),
    .Q(\a_reg[0] ),
    .RESET_B(rst_n)
  );
endmodule
